package edu.isi.policy.test;

import edu.isi.policy.entity.Transfer;
import edu.isi.policy.util.TransferList;

rule "Add transfers that aren't to jacoby.isi.edu into memory"
when
	$transferList: TransferList(size() > 0)
	$t: Transfer(destination.getHost() != "jacoby.isi.edu") from $transferList
then
    insert($t);
end 

rule "Remove transfers from the list that are to jacoby.isi.edu"
when
    $transferList: TransferList(size() > 0)
    $t: Transfer(destination.getHost() == "jacoby.isi.edu" ) from $transferList
then
    modify($transferList) {
        remove($transferList.indexOf($t))
    }
end